
import type { GeneratedReport } from './reportTypes.js';

export function renderMarkdown(report: GeneratedReport): string {
  const { project, projectFindings, security, recommendations, generatedAt } = report;

  let md = `# Technical Audit Report\n\n`;

  md += `## Metadata\n`;
  md += `- **Generated at**: ${generatedAt}\n`;
  md += `- **Path**: \`${project.cwd}\`\n`;
  md += `- **Project type**: ${project.type.toUpperCase()}\n`;
  md += `- **Package manager**: ${project.packageManager}\n\n`;

  md += `## Project Overview\n`;
  md += `- **Tests**: ${project.hasTests ? '✅ Detected' : '❌ Not found'}\n`;
  md += `- **CI/CD**: ${project.hasCI ? '✅ Detected' : '❌ Not found'}\n`;
  md += `- **Docker**: ${project.hasDockerfile ? '✅ Detected' : '❌ Not found'}\n`;
  md += `- **Files detected**: ${project.detectedFiles.join(', ') || 'None'}\n`;
  md += `- **Directories detected**: ${project.detectedDirectories.join(', ') || 'None'}\n\n`;

  if (projectFindings.length > 0) {
    md += `## Project Structure Findings\n`;
    for (const f of projectFindings) {
      md += `- [${f.severity.toUpperCase()}] ${f.message}\n`;
    }
    md += `\n`;
  }

  md += `## Security Summary\n`;
  md += `- **Critical**: ${security.severitySummary.critical}\n`;
  md += `- **High**: ${security.severitySummary.high}\n`;
  md += `- **Medium**: ${security.severitySummary.medium}\n`;
  md += `- **Low**: ${security.severitySummary.low}\n`;
  md += `- **Info**: ${security.severitySummary.info}\n\n`;

  if (security.findings.length > 0) {
    md += `## Security Findings\n\n`;
    for (const f of security.findings) {
      md += `### [${f.source}][${f.severity.toUpperCase()}] ${f.title}\n`;
      if (f.source === 'semgrep') {
        md += `- **File**: \`${f.file}:${f.line}\`\n`;
        md += `- **Rule**: \`${f.ruleId}\`\n`;
      } else if (f.source === 'trivy') {
        md += `- **Package**: \`${f.packageName}\`\n`;
        md += `- **Installed**: \`${f.installedVersion}\`\n`;
        if (f.fixedVersion) md += `- **Fixed**: \`${f.fixedVersion}\`\n`;
        md += `- **Vulnerability**: \`${f.vulnerabilityId}\`\n`;
        md += `- **Target**: \`${f.target}\`\n`;
      }
      md += `- **Description**: ${f.description}\n\n`;
    }
  } else {
    md += `*No security findings detected.*\n\n`;
  }

  if (security.warnings.length > 0) {
    md += `## Warnings\n`;
    for (const w of security.warnings) {
      md += `- ${w}\n`;
    }
    md += `\n`;
  }

  if (recommendations.length > 0) {
    md += `## Recommendations\n`;
    for (const r of recommendations) {
      md += `- ${r}\n`;
    }
    md += `\n`;
  }

  md += `---\n*Report generated by OpenClaude Derived Audit Tool.*`;

  return md;
}
